<a href="https://colab.research.google.com/github/loyedan/ELAIS--QST-2024-25-GH/blob/main/Linear_Algrebra_with_Python_Vectors_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Linear Algrebra with Python - Vectors**

### **Vectors**

Hilbert Space

In [ ]:
import numpy as np

lt1 = [1, 2, 3]
lt2 = [4, 5, 6]

vec1 = np.array(lt1)
vec2 = np.array(lt2)

print(lt1)
print(type)(lt1)
print(vec1)
print(type)(vec1)

[1, 2, 3]
<class 'type'>


TypeError: 'NoneType' object is not callable

In [ ]:
import numpy as np


def lt_vec_add(lt1, lt2):
    lt_add = []
    lt_add] = [lt1[i] + lt2[i] for i in range(len(lt1)) #list comprehension
    return lt_add


lt1 = [1, 2, 3]
lt2 = [4, 5, 6]

vec1 = np.array(lt1)
vec2 = np.array(lt2)

print(lt1)
print(type(lt1)) # removed extraneous parenthesis after type
print(vec1)
print(type(vec1))

[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


An array is a data structure that stores a collection of elements of the same data type. You can access these elements using their index.

In your code, vec1 and vec2 are arrays created from lists using np.array().

In [ ]:
vec_add = vec1 + vec2
lt_add = lt1 + lt2
lt_vec_add1 = lt_vec_add(lt1, lt2)
print(vec_add)
lt_add = lt1 + lt2
print("vector addition is: " + str(vec_add))
print("list addition is: " + str(lt_add))

vec_sub = vec1 - vec2
print("vector subtraction is: " + str(vec_sub))

vec_mult = vec1 * vec2
print("vector multiplication is: " + str(vec_mult))

vec_div = vec1 / vec2
print("vector division is: " + str(vec_div))

NameError: name 'lt_vec_add' is not defined

In [ ]:
import numpy as np
from sympy import symbols, Matrix

x1, x2, x3

def lt_vec_add(lt1, lt2):
    lt_add = []
    lt_add = [lt1[i] + lt2[i] for i in range(len(lt1))] #list comprehension
    return lt_add


lt1 = [1, 2, 3]
lt2 = [4, 5, 6]

vec1 = np.array(lt1)
vec2 = np.array(lt2)

print(lt1)
print(type(lt1)) # removed extraneous parenthesis after type
print(vec1)
print(type(vec1))

vec_add = vec1 + vec2
lt_add = lt1 + lt2
lt_vec_add1 = lt_vec_add(lt1, lt2) # This will now work if the cell above is executed first.
print(vec_add)
lt_add = lt1 + lt2
print("vector addition is: " + str(vec_add))
print("list addition is: " + str(lt_add))

vec_sub = vec1 - vec2
print("vector subtraction is: " + str(vec_sub))

vec_mult = vec1 * vec2
print("vector multiplication is: " + str(vec_mult))

vec_div = vec1 / vec2
print("vector division is: " + str(vec_div))

vec_dot_pro = vec1.dot(vec2)
vec_cross = np.cross(vec1, vec2)
print("vector dot product is : " + str(vec_dot_pro))
print("vector cross product is : " + str(vec_cross))


[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>
[5 7 9]
vector addition is: [5 7 9]
list addition is: [1, 2, 3, 4, 5, 6]
vector subtraction is: [-3 -3 -3]
vector multiplication is: [ 4 10 18]
vector division is: [0.25 0.4  0.5 ]
vector dot product is : 32
vector cross product is : [-3  6 -3]


In [ ]:
import numpy as np
from sympy import symbols, Matrix

x1, x2, y1, y2, z1, z2 = symbols('x1 x2 y1 y2 z1 z2')

def lt_vec_add(lt1, lt2):
    lt_add = []
    lt_add = [lt1[i] + lt2[i] for i in range(len(lt1))] #list comprehension
    return lt_add


lt1 = [1+2j, 2, 3]
lt2 = [4, 5, 6]
slt1 = [x1, y1, z1]
slt2 = [x2, y2, z2]
vec1 = np.array(lt1)
vec2 = np.array(lt2)
svec1 =

print(lt1)
print(slt1)
# print(type(lt1)) # removed extraneous parenthesis after type
print(vec1)
print(svec1)
# print(type(vec1))


vec_add = vec1 + vec2
lt_add = lt1 + lt2
lt_vec_add1 = lt_vec_add(lt1, lt2) # This will now work if the cell above is executed first.
print(vec_add)
lt_add = lt1 + lt2
print("vector addition is: " + str(vec_add))
print("list addition is: " + str(lt_add))


'''
vec_sub = vec1 - vec2
print("vector subtraction is: " + str(vec_sub))

vec_mult = vec1 * vec2
print("vector multiplication is: " + str(vec_mult))

vec_div = vec1 / vec2
print("vector division is: " + str(vec_div))

vec_dot_pro = vec1.dot(vec2)
vec_cross = np.cross(vec1, vec2)
print("vector dot product is : " + str(vec_dot_pro))
print("vector cross product is : " + str(vec_cross))
'''

[(1+2j), 2, 3]
[x1, y1, z1]
[1.+2.j 2.+0.j 3.+0.j]


NameError: name 'svec1' is not defined