<a href="https://colab.research.google.com/github/loyedan/ELAIS--QST-2024-25-GH/blob/main/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Linear Algebra with Python**

# **Dot Product**

# **Exmaple 1**

In [2]:
import numpy as np

# lets define our vectors
u = [-3, -2, 0, -1, 4]
v = [-1, -1, 2, -3, 5]

uv = 0 # summation is iniitally zero

for i in range(len(u)): # iterativelly access every pair with the same indices
  print("pairwise multiplication of the entries with index", i, "is", u[i]*v[i])
  uv = uv + u[i]*v[i] # i-th entries are multiplied and then added to summation

  print() # print an empty line
  print("The dot product of", u, "and", v, "is", uv)



pairwise multiplication of the entries with index 0 is 3

The dot product of [-3, -2, 0, -1, 4] and [-1, -1, 2, -3, 5] is 3
pairwise multiplication of the entries with index 1 is 2

The dot product of [-3, -2, 0, -1, 4] and [-1, -1, 2, -3, 5] is 5
pairwise multiplication of the entries with index 2 is 0

The dot product of [-3, -2, 0, -1, 4] and [-1, -1, 2, -3, 5] is 5
pairwise multiplication of the entries with index 3 is 3

The dot product of [-3, -2, 0, -1, 4] and [-1, -1, 2, -3, 5] is 8
pairwise multiplication of the entries with index 4 is 20

The dot product of [-3, -2, 0, -1, 4] and [-1, -1, 2, -3, 5] is 28


# **Exmaple 2**

In [3]:
# let's find the dot product of a  and b
a = [-4, 0]
b = [0, -5]
result = 0

for i in range(2):
  result = result + a[i]*b[i]

print("the dot product of a and b is", result)

the dot product of a and b is 0


# **Exmaple 3**

In [5]:
x = [-3, 2, 4, 6, 7, 10, 20]
y = [1, 5, -11, -12, 9, 8, 7]

dot_prod = 0 # a container

for i in range(7):
  dot_prod = dot_prod + x[i]*y[i]

print("the dot product of x and y is", dot_prod)

the dot product of x and y is 174


x = [1, 2]
x1 = np.array([1], [2]) # matrices
print(x)
print(x1)

x.dtype
x1.shape

# **Eigenvalues and Eigenvectors**

# **Example 1**

In [11]:
import numpy as np
A = np.array([[1, 6],
             [5, 3]])

# finding eigenvalues and eigenvectors
vals, vecs, = np.linalg.eig(A)
print("The eigenvalues of A are", vals)

print("The eigenvectors of A are", vecs) # the whole of the eigenvectors
print(vecs[:, 0]) # print my first column
print(vecs[:, 1]) # print the second column

The eigenvalues of A are [-3.56776436  7.56776436]
The eigenvectors of A are [[-0.7956659  -0.67447444]
 [ 0.60573573 -0.7382982 ]]
[-0.7956659   0.60573573]
[-0.67447444 -0.7382982 ]


# **Example 2**

In [13]:
B = np.array([[1, 2],
              [4, 5]])

vals, vecs = np.linalg.eig(B)
print("The eigenvalues of B are", vals)
print("The eigenvectors of B are", vecs)

The eigenvalues of B are [-0.46410162  6.46410162]
The eigenvectors of B are [[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


## **Linear Operators**

# **Example 1**

In [18]:
"""
from math import cos, sin, pi
import numpy as np

def
"""

'\nfrom math import cos, sin, pi\nimport numpy as np\n\ndef\n'

In [15]:
"""
This is
a multiline
comment
"""

'\nThis is\na multiline\ncomment\n'

In [14]:
# This is
# a multiline
# comment

# *Teach Python fuctions then continue from opeerators*

# **Tensor Product**

# **Example 1**

In [19]:
import numpy as np

# Define two complex vectors u and v
u = np.array([1+2j, 3 -1j])
u = np.array([2 -1j, 4 +3j])

# Compute the dot product using conjugate transpose for u
dot_product = np.vdot(u, v) # vdot takes the conjugate transpose of the first argument

# Compute the element-wise product
element_wise_product = np.multiply(u, v)

print("Dot Product:", dot_product)

ValueError: cannot reshape array of size 5 into shape (2,)

# **Example 2**

In [20]:
import numpy as np
A = np.array([[1, 0], [0, 1]])

print(A)

B = np.array([[1, 3], [4, 2]])

print(B)

np.kron(A, B) # Performs a tensor product on A and B

[[1 0]
 [0 1]]
[[1 3]
 [4 2]]


array([[1, 3, 0, 0],
       [4, 2, 0, 0],
       [0, 0, 1, 3],
       [0, 0, 4, 2]])

# **Example 3**

In [22]:
v = [1, 2, 3]
u = [-2, 3]

vu = []

for i in range(len(v)): # each element of v will be replaced
  for j in range(len(u)): # the vector of u will come here after multiplying with the entry there
    vu.append(v[i]*u[j])

print("v =", v)
print("u =", u)
print("vu =", vu)

v = [1, 2, 3]
u = [-2, 3]
vu = [-2, 3, -4, 6, -6, 9]
